import { ClientOnlyToaster } from "@/components/ClientOnlyToaster";
import NetworkStatusProvider from "@/components/NetworkStatusProvider";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/redux/ReduxProvider";
import ClientLayout from "./ClientLayout";

const dmSans = DM_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nursery Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} antialiased`}>
        <ClientOnlyToaster />
        <NetworkStatusProvider>
          <ReduxProvider>
            <ClientLayout>{children}</ClientLayout>
          </ReduxProvider>
        </NetworkStatusProvider>
      </body>
    </html>
  );
}
